### ISSUE TITLE
[BUG] Not able to retrieve complete information in staging demo

### ISSUE THREAD

**Issue by Jiltseb** [mobiusml/aana_sdk#136] opened 2024-07-12 12:59 UTC
### Bug Description
- The chat output is cut off at a certain duration before the length of the video, when asked to produce captions for entire duration of video with timestamps.

### Steps to Reproduce
1. Go to staging demo and insert the link for a YouTube video that is 10 minutes duration for example.
2. Ask it to generate visual captions with timestamps (start,end) for the complete length of video.
3. Output is limited to certain duration of the video (in my test case 200sec). This is owing to the VLLM output length limitation, and this needs to be bypassed by providing multiple chunks as output.

### Expected Behavior
- Generates visual captions for the complete video, even if they occur as chunks per call. For example, each output can correspond to 3 mins and x such chunks.

### Actual Behavior
- captions abruptly cut after a certain duration.

**Comment by movchan74** [comment] 2024-07-15 12:25
Thank you for reporting this issue. We've identified the cause and have some suggestions for resolving it.

@Jiltseb, could you please confirm that I've understood the issue correctly? If I've misinterpreted anything, please let me know.

## Root Cause

The output limitation you're experiencing is due to a default token limit in the LLM configuration:

- Default token limit: 1024 tokens
- Location of this setting: [aana/configs/deployments.py, line 77](https://github.com/mobiusml/aana_sdk/blob/556b9fb27445b5deb7d9e38ddd2c1d0a698fa9d7/aana/configs/deployments.py#L77)

This limitation is causing the captions to be cut off prematurely for longer videos.

## Proposed Solutions

### 1. Modify the max_tokens parameter

To address this issue, we can increase the `max_tokens` value. This can be done in two ways:

a) In the web app request:
   - Modify the request to the `/video/chat_stream` endpoint
   - Provide `sampling_params` with an increased `max_tokens` value

b) In the Chat with video app:
   - Change the default `max_tokens` value in the app configuration

I recommend implementing this change in the web app request for more flexibility.

@HRashidi, could you please look into implementing this change? If you need any additional information or context, please let me know.

### 2. Fetch captions from the database

It's worth noting that:
- Captions are generated and stored in our database
- While it's possible to ask the LLM to return captions, fetching from the database would be more efficient and precise
- The current Chat with Video app doesn't have an endpoint for this, but we can easily add one if needed

## Next Steps

@HRashidi to implement the `max_tokens` modification in the web app request.

Please let me know if anyone needs further clarification or questions about implementing these solutions.

**Comment by Jiltseb** [comment] 2024-07-15 13:34
Having a staging demo that has everything in it (captions, transcriptions, chats) is beneficial for an easier development process. I don't have to run the SDK myself, but I can still get the captions (in my case, I need this output to provide additional context to the audio description generator while testing). If it's not recommended to use chat for this, whats the best way I can get it from the staging demo?

I meant the `max_tokens` at the output that can be passed to the user, not the `context_length` passed to the LLM. (`max_length` in the decoder). Is it enough for a 10 minute video?

**Comment by appoose** [comment] 2024-09-23 14:38
The current decision is to define and call an endpoint if it is neccesary. We have decided not to do this in the frontend. So closing the ticket. Please open a new one if this becomes a priority again.

**Closed by appoose** 2024-09-23 14:38 UTC
Labels: bug
